version: "2"
services:
  linotp:
    image: linotp:latest
    environment:
      LINOTP_DB_TYPE: "postgres"
      LINOTP_DB_HOST: "linotp-db"
      LINOTP_DB_PORT: "5432"
      LINOTP_DB_USER: "linotpuser"
      LINOTP_DB_PASSWORD: "linotppass"
      LINOTP_DB_NAME: "linotp_db"
    depends_on:
      - linotp-db
    ports:
      - "443:443"

  linotp-db:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: "linotp_db"
      POSTGRES_PASSWORD: "linotppass"
      POSTGRES_USER: "linotpuser"
    volumes:
    - /var/lib/postgresql/data/pgdata
